# Generated by Django 6.0.1 on 2026-04-06 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.CharField(blank=True, max_length=50, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('job_type', models.CharField(blank=True, choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('internship', 'Internship'), ('contract', 'Contract'), ('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'Onsite')], max_length=100, null=True)),
                ('posted_date', models.CharField(blank=True, max_length=50, null=True)),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('naukri', 'Naukri')], max_length=20)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('apply_link', models.URLField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_score', models.FloatField(blank=True, default=0.0, null=True)),
                ('star_rating', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-match_score', '-created_at'],
            },
        ),
    ]
