# Generated by Django 6.0.1 on 2026-04-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='role_category',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
